### ISSUE TITLE
meson build fails on clean install

### ISSUE THREAD

**Issue by jrgeraci** [nnstreamer/nntrainer#1853]
On Ubuntu 20.04 WSL2 AND normal Ubuntu 20.04 
After following the instructions on 
https://github.com/nnstreamer/nntrainer/blob/main/docs/getting-started.md#build-with-meson
meson build fails to find
Run-time dependency capi-ml-inference found: NO (tried pkgconfig and cmake)
and thereby fails with
nntrainer/layers/meson.build:58:4: ERROR: Problem encountered: NNStreamer CAPI dependency not found

CC:@myungjoo This may be an nnstreamer api related issue as nnstreamer-examples also fails to find this.

```
(base) jrgeraci@MSI:~/nntrainer$ meson build
The Meson build system
Version: 0.53.2
Source dir: /home/jrgeraci/nntrainer
Build dir: /home/jrgeraci/nntrainer/build
Build type: native build
Project name: nntrainer
Project version: 0.3.0
C compiler for the host machine: cc (gcc 9.4.0 "cc (Ubuntu 9.4.0-1ubuntu1~20.04) 9.4.0")
C linker for the host machine: cc ld.bfd 2.34
C++ compiler for the host machine: c++ (gcc 9.4.0 "c++ (Ubuntu 9.4.0-1ubuntu1~20.04) 9.4.0")
C++ linker for the host machine: c++ ld.bfd 2.34
Host machine cpu family: x86_64
Host machine cpu: x86_64
Compiler for C supports arguments -Wredundant-decls: YES
Compiler for C++ supports arguments -Wredundant-decls: YES
Compiler for C supports arguments -Wwrite-strings: YES
Compiler for C++ supports arguments -Wwrite-strings: YES
Compiler for C supports arguments -Wformat: YES
Compiler for C++ supports arguments -Wformat: YES
Compiler for C supports arguments -Wformat-nonliteral: YES
Compiler for C++ supports arguments -Wformat-nonliteral: YES
Compiler for C supports arguments -Wformat-security: YES
Compiler for C++ supports arguments -Wformat-security: YES
Compiler for C supports arguments -Winit-self: YES
Compiler for C++ supports arguments -Winit-self: YES
Compiler for C supports arguments -Waddress: YES
Compiler for C++ supports arguments -Waddress: YES
Compiler for C supports arguments -Wno-multichar -Wmultichar: YES
Compiler for C++ supports arguments -Wno-multichar -Wmultichar: YES
Compiler for C supports arguments -Wvla: YES
Compiler for C++ supports arguments -Wvla: YES
Compiler for C supports arguments -Wpointer-arith: YES
Compiler for C++ supports arguments -Wpointer-arith: YES
Compiler for C supports arguments -Wno-error=varargs -Werror=varargs: YES
Compiler for C++ supports arguments -Wno-error=varargs -Werror=varargs: YES
Compiler for C supports arguments -Wdefaulted-function-deleted: NO
Compiler for C++ supports arguments -Wdefaulted-function-deleted: NO
Compiler for C supports arguments -ftree-vectorize: YES
Compiler for C++ supports arguments -ftree-vectorize: YES
Compiler for C supports arguments -Wmissing-declarations: YES
Compiler for C supports arguments -Wmissing-include-dirs: YES
Compiler for C supports arguments -Wmissing-prototypes: YES
Compiler for C supports arguments -Wnested-externs: YES
Compiler for C supports arguments -Waggregate-return: YES
Compiler for C supports arguments -Wold-style-definition: YES
Compiler for C supports arguments -Wdeclaration-after-statement: YES
Compiler for C supports arguments -Wno-error=varargs -Werror=varargs: YES
Program sh found: YES (/usr/bin/sh)
Found pkg-config: /usr/bin/pkg-config (0.29.1)
Found CMake: /usr/bin/cmake (3.16.3)
Run-time dependency blas-openblas found: NO (tried pkgconfig and cmake)
Run-time dependency openblas found: YES 0.3.8
Run-time dependency OpenMP found: YES 4.5
Library m found: YES
Library dl found: YES
Run-time dependency threads found: YES
Dependency iniparser found: NO found 3.2 but need: '>=4.1'
Run-time dependency iniparser found: NO (tried pkgconfig and cmake)
Message: falling back to find libiniparser library and header files
Library iniparser found: YES
Has header "iniparser.h" : YES
Run-time dependency capi-ml-inference found: NO (tried pkgconfig and cmake)
Run-time dependency capi-ml-common found: YES 1.8.0
Run-time dependency tensorflow2-lite found: YES 2.7.0
Run-time dependency GTest found: YES 1.10.0
Run-time dependency GTest found: YES 1.10.0
Run-time dependency opencv found: NO (tried pkgconfig and cmake)
Run-time dependency opencv4 found: YES 4.2.0
Program flatc found: YES (/usr/bin/flatc)
Configuring nntrainer.pc using configuration
Configuring nntrainer.ini using configuration
Message: NNTRAINER_CONF_PATH=/usr/local/etc/nntrainer.ini
Message: extra defines are:-DMIN_CPP_VERSION=201703L -DUSE_BLAS=1 -D__LOGGING__=1 -DENABLE_TEST=1 -DREDUCE_TOLERANCE=1 -DENABLE_NNSTREAMER_BACKBONE=1 -DENABLE_TFLITE_BACKBONE=1 -DENABLE_TFLITE_INTERPRETER=1 -DENABLE_DATA_AUGMENTATION_OPENCV=1 -DNNTRAINER_CONF_PATH="/usr/local/etc/nntrainer.ini"

nntrainer/layers/meson.build:58:4: ERROR: Problem encountered: NNStreamer CAPI dependency not found
```

**Comment by jrgeraci** [comment]
It seems the below requirements aren't being installed.
Could you help me find them?

```
(base) jrgeraci@MSI:~$ pkg-config capi-ml-inference --print-errors
Package capi-nnstreamer-single was not found in the pkg-config search path.
Perhaps you should add the directory containing `capi-nnstreamer-single.pc'
to the PKG_CONFIG_PATH environment variable
Package 'capi-nnstreamer-single', required by 'capi-ml-inference', not found
```

**Comment by zhoonit** [comment]
nntrainer build is relying on capi-ml-inference.(due to layer using nnstreamer and capi).

After, https://github.com/nnstreamer/api/pull/131/files#r823877660 making capi-ml-inference.pc requires capi-ml-inference-[single|pipeline].pc

https://github.com/nnstreamer/api/blob/main/debian/ml-inference-api-dev.install
should be including capi-ml-inference-[single|pipeline].pc files as well which seems to be omitted.

quick solution (just for now) would be building and installing https://github.com/nnstreamer/api  manually, but should be fixed soon.

**Comment by myungjoo** [comment]
@zhoonit @lhs8928 : Although Ubuntu users can install devel packages of api.git and nnstreamer.git and build nntrainer, it is still not very portable for novice users. Let's discuss the issue next Monday whenever you are available in the office.

**Comment by eli-schwartz** [comment]
In e.g. https://github.com/nnstreamer/api/blob/main/c/meson.build there are meson `declare_dependency` interface dependencies. You can use these to power https://mesonbuild.com/Wrap-dependency-system-manual.html

What you would do is add a `subprojects/nnstreamer-api.wrap` file (technically it can be called whatever you want) containing a reference to how to download api.git, and a `[provide]` section mapping each pkg-config dependency name to the subproject `declare_dependency` that provides that pkg-config dependency.

Users would then build nntrainer as normal. If capi-ml-inference is not found on the system, novice users don't need to worry about figuring out devel packages! Meson will simply find that in the `[provide]` section of an available wrap file, download api.git, and build it as part of nntrainer. Running `meson install` will then install both nntrainer and api.

More knowledgeable users have the tools to choose whether that is allowed. People who do not like this behavior may simply configure Meson with `--wrap-mode=nodownload` (or nofallback) to prevent resolving subprojects. Users who want to explicitly ignore the system version can use the value "forcefallback".

**Comment by myungjoo** [comment]
@eli-schwartz Yes, I agree with you. I'll add a fallback header in case the api package is not available.

**Comment by myungjoo** [comment]
@jijoongmoon , @lhs8928 : are you good with #1861 approach?
I'd like to make the dependency on ML-API and nnstreamer "optional" in non-Tizen environments.

**Comment by lhs8928** [comment]
I am good with it

**Comment by myungjoo** [comment]
with #1861 , in Ubuntu, clean meson build without nnstreamer or ml-api works.
